-- Run once in the Supabase SQL editor, before configuring the site.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text not null unique check (username = lower(username) and username ~ '^[a-z0-9_]{3,40}$'), role text not null default 'editor' check (role in ('admin','editor')), created_at timestamptz not null default now());
create table if not exists public.obras_sociales (id uuid primary key default gen_random_uuid(), name text not null, normalized_name text generated always as (lower(regexp_replace(trim(name), '\\s+', ' ', 'g'))) stored, active boolean not null default true, logo_url text, official_url text, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), constraint obras_sociales_name_unique unique(normalized_name), constraint obras_sociales_name_not_blank check(length(trim(name)) > 0), constraint obras_sociales_logo_url check(logo_url is null or logo_url ~ '^https://'), constraint obras_sociales_official_url check(official_url is null or official_url ~ '^https://'));
create table if not exists public.obras_sociales_audit (id bigint generated always as identity primary key, obra_social_id uuid references public.obras_sociales(id) on delete set null, actor_id uuid references auth.users(id) on delete set null, action text not null check(action in ('created','edited','activated','deactivated','deleted')), before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
create or replace function public.is_coverage_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;
create or replace function public.set_coverage_metadata() returns trigger language plpgsql security definer set search_path = public as $$ begin new.updated_at := now(); new.updated_by := auth.uid(); if tg_op = 'INSERT' then new.created_by := auth.uid(); end if; return new; end; $$;
create or replace function public.audit_coverage_change() returns trigger language plpgsql security definer set search_path = public as $$ declare event_action text; begin if tg_op = 'INSERT' then insert into public.obras_sociales_audit (obra_social_id,actor_id,action,after_data) values(new.id,auth.uid(),'created',to_jsonb(new)); return new; elsif tg_op = 'DELETE' then insert into public.obras_sociales_audit (obra_social_id,actor_id,action,before_data) values(old.id,auth.uid(),'deleted',to_jsonb(old)); return old; end if; event_action := case when old.active is distinct from new.active then case when new.active then 'activated' else 'deactivated' end else 'edited' end; insert into public.obras_sociales_audit (obra_social_id,actor_id,action,before_data,after_data) values(new.id,auth.uid(),event_action,to_jsonb(old),to_jsonb(new)); return new; end; $$;
drop trigger if exists obras_sociales_metadata on public.obras_sociales;
create trigger obras_sociales_metadata before insert or update on public.obras_sociales for each row execute function public.set_coverage_metadata();
drop trigger if exists obras_sociales_audit_log on public.obras_sociales;
create trigger obras_sociales_audit_log after insert or update or delete on public.obras_sociales for each row execute function public.audit_coverage_change();
alter table public.profiles enable row level security; alter table public.obras_sociales enable row level security; alter table public.obras_sociales_audit enable row level security;
create policy "Administrators can read profiles" on public.profiles for select to authenticated using (public.is_coverage_admin());
create policy "Administrators manage coverage" on public.obras_sociales for all to authenticated using (public.is_coverage_admin()) with check (public.is_coverage_admin());
create policy "Administrators read audit" on public.obras_sociales_audit for select to authenticated using (public.is_coverage_admin());
create or replace view public.obras_sociales_public as select id,name,logo_url,official_url,description,updated_at from public.obras_sociales where active = true;
grant select on public.obras_sociales_public to anon, authenticated;
insert into public.obras_sociales (name) values ('ACTIVA SALUD'),('AMEBPBA'),('AMFFA'),('AMSTERDAM SALUD'),('APSOT'),('ASOCIACIÓN ECLESIÁSTICA SAN PEDRO'),('AVALIAN SALUD Y BIENESTAR'),('CASA'),('CENTRO MEDICO PUEYRREDON'),('COLEGIO DE ESCRIBANOS'),('COLONIA SUIZA'),('COMEI'),('DASMI'),('DASUTEN'),('E. W. HOPE'),('FEDERADA SALUD'),('FUTBOLISTAS'),('GLOBAL EMPRESARIA SA'),('IOMA'),('JERARQUICOS'),('LA SEGUNDA PERSONAS'),('LPF GRUPO LA PEQUEÑA FAMILIA'),('LUIS PASTEUR'),('MEDICAR WORK'),('MEDIFE SA'),('OPDEA'),('OSAP'),('OSCAP'),('OSDOP'),('OSETRA'),('OSFATUN'),('OSPE'),('OSPEDYC'),('OSPEP Personal de Panaderías'),('OSPEPBA'),('OSPIA'),('OSPTV'),('OSSEG'),('PODER JUDICIAL'),('PREVENCION SALUD S.A'),('RAS'),('SANCOR'),('SCIS S.A.'),('SWISS MEDICAL S.A.') on conflict (normalized_name) do nothing;
-- Create the admin in Authentication, then run once with its UUID:
-- insert into public.profiles (id,username,role) values ('AUTH_USER_UUID','kinesiologiakareh','admin');
